name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Poetry
        uses: step-security/install-poetry@8cee588dbbc9ca4f2882c176ce61917303942193 # v1.4.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: pyproject.toml
          cache: poetry

      - name: Check lockfile
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --no-interaction --sync

      - name: Lint Check
        run: poetry run ruff check .

      - name: Format Check
        run: poetry run ruff format --check .

      - name: Run Tests
        run: poetry run pytest